[project]
name = "langgraph-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langgraph>=0.6.3",
    "langchain-ollama>=0.1.0",
    "streamlit>=1.28.0",
    "pydantic>=2.5.0",
    "ollama>=0.3.0",
]
